### ISSUE TITLE
Building always has to recompile rebar3 dependencies

### ISSUE THREAD

**Issue by schneebyte** [cw789/elixir_nix_example#4]
mix_build.nix could be changed to only compile the dependencies.
Then when building the release all deps wouldn't have to be recompiled every single time.

---

Initial issue title: **Building release always has to compile all dependencies**

**Comment by cw789** [comment]
I've added separate `mix_deps_build` step now, in which the `libs` folder is not included.
This should now only recompile `deps` if `config/`, `mix.exs` or `mix.lock` has changed (not sure if `mix.exs` is required here?).

But I have longer the circumstance, that rebar3 deps are always recompiled!?
Don't now why at the moment.

**Comment by cw789** [comment]
Notes to myself.
› https://elixirforum.com/t/how-to-cache-erlang-builds-on-ci/14789/24
› https://github.com/erlang/rebar3/issues/1627

**Comment by schneebyte** [comment]
Well at least it saves the elixir deps from recompiling for now

Thank you!

**Comment by cw789** [comment]
Your are welcome.
Thanks for the honor of giving your first star & issue to me.

Let me know if you encounter anything else.

**Comment by schneebyte** [comment]
I think i found a fix.
When i change build_embedded to true in mix.exs it doesn't recompile the rebar3 deps anymore.

**Comment by cw789** [comment]
Cool fix.

I found out it wouldn't be necessary anymore with Elixir v1.12.
→ https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/tasks/deps.compile.ex#L196-L205

Elixir mix deps.compile will then use `REBAR_BARE_COMPILER_OUTPUT_DIR` default set to `_build`.
So then compiled rebar3 things won't land in `deps` anymore...

The merge request about this: https://github.com/elixir-lang/elixir/pull/10018

**Comment by cw789** [comment]
Just to inform.

The `REBAR_BARE_COMPILER_OUTPUT_DIR` usage was removed again in Elixir v1.12. (caused by issue https://github.com/elixir-lang/elixir/issues/10978).

This means the usage of `build_embedded: true` in mix.exs would still be necessary.
